---

  - name: Ensure SABnzbd service user is present
    user: name={{ sabnzbd_user_name }}
          home=/home/{{ sabnzbd_user_name }}
          createhome=yes
          state=present

  - name: Add Current APT Repo for SABnzbd
    apt_repository: repo='ppa:jcfp/ppa' state=present update_cache=yes
    register: PPAInstalled

  ## Check/Install Dependencies for SABnzbd
  - name: Ensure SABnzbd dependencies are installed
    apt: name={{ item }} state=present
    with_items:
      - git
      - par2
      - python
      - python-cheetah
      - python-configobj
      - python-feedparser
      - unrar
      - unzip

  - name: Install SABnzbd from repository
    apt: pkg=sabnzbdplus state=latest
    when: PPAInstalled|success

  # Create SABnzdb Data location
  - name: Ensure SABnzbd data directory exists
    file: dest={{ sabnzbd_data_location }}
          owner={{ sabnzbd_user_name }}
          group={{ sabnzbd_group_name }}
          recurse=yes state=directory

  ## Deploys default file for SABnzbd
  - name: Deploy SABnzbd init.d default file
    template: dest=/etc/default/sabnzbdplus
              src=ubuntu.default.j2
              owner=root group=root mode=755
    #notify: start sabnzbdplus
              
  - name: Ensure SABnzbd service is running and enabled on boot
    service: name=sabnzbdplus state=started enabled=yes
