FROM ubuntu:12.04

RUN sed -i -e 's/archive.ubuntu.com/au.archive.ubuntu.com/g' /etc/apt/sources.list
RUN apt-get update

# Install Ansible
RUN apt-get install -y software-properties-common git
RUN apt-add-repository -y ppa:ansible/ansible
RUN add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu precise multiverse"
RUN apt-get update
RUN apt-get install -y ansible

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
